### ISSUE TITLE
assignment 2

### ISSUE THREAD

**Issue by HadarKlimovski** [Stavoh/Trial-1#3]
The submission of assignment 2 is over, and I saw that you did not submit it. Are you continuing the course?
Hadar
@Stavoh

**Comment by Stavoh** [comment]
Yes, I just struggle with the assignment

**Comment by HadarKlimovski** [comment]
Why didn't you ask for help? Im here to any question

**Comment by Stavoh** [comment]
> Why didn't you ask for help? Im here to any question

I didn't realize we only got 4 days to complete the assignment. Really, why set the deadline that soon?
